projects:
  default:
    schema: https://countries.trevorblades.com/
    documents: your_documents/*.graphql
    extensions:
      turms:
        out_dir: your_library
        stylers:
          - type: turms.stylers.capitalize.CapitalizeStyler
          - type: turms.stylers.snake_case.SnakeCaseStyler
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operations.OperationsPlugin
        processors:
          - type: turms.processors.black.BlackProcessor
          - type: turms.processors.isort.IsortProcessor
        scalar_definitions:
          uuid: str
          UUID: str
          Callback: str
          Any: typing.Any
          QString: str
          ID: str
