projects:
  default:
    schema: beasts.graphql
    extensions:
      turms:
        out_dir: examples/countries-code/api
        parsers:
          - type: turms.parsers.polyfill.PolyfillParser
            python_version: 3.7
        stylers:
          - type: turms.stylers.capitalize.CapitalizeStyler
          - type: turms.stylers.snake_case.SnakeCaseStyler
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.strawberry.StrawberryPlugin
        processors:
          - type: turms.processors.disclaimer.DisclaimerProcessor
          - type: turms.processors.black.BlackProcessor
          - type: turms.processors.isort.IsortProcessor
          - type: turms.processors.merge.MergeProcessor
        scalar_definitions:
          uuid: str
          UUID: str
          Callback: str
          Any: typing.Any
          QString: str
          ID: str
